/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example; // 

import com.alibaba.fastjson2.*;
import org.example.my_class.Gun; // 在gradle项目中引包时, 也是直接从'org'目录开始 (导入Gun类), 注意不是java开头! ()

public class App {
    // 在本项目中, 我们运用了Gradle脚手架创建了项目, 现在这个项目只需通过设置build.gradle即可轻松的导入和管理各种第三方包
    // 我们来尝试导入第三方的json包玩一下序列化
    public static void main(String[] args) {
        System.out.println("当前取得的用户工作路径为: "+System.getProperty("user.dir"));
        Gun smg = new Gun("Mac-10", ".45 ACP", false, 114514);
        System.out.println("已创建枪的名称为: " + smg.get_name() + ", 子弹类型为: " + smg.get_ammo_type() + ", 枪的id为: " + smg.get_gun_id());

        String gun_json = JSON.toJSONSTring(smg);
        System.out.println(gun_json);
    }


}
